### PR TITLE
Fix wrong link

### PR DESCRIPTION
**Pull request by bastilimbach**
The link to the angular 2 article and the vue result app didn't work. So I fixed it 🎉 
Btw, great article 👍

### CODE REVIEW

**Comment by bastilimbach** [comment]
@jeremenichelli Also the vue result app seems to be broken.

**Comment by jeremenichelli** [comment]
Well, looks like I don't know how to properly link pages 😆 thanks a lot for the fixes and the kind of words 🍻

**Comment by jeremenichelli** [comment]
Not merging cause the Vue link actually should point to the repository and not the app. But I will fix those two. Thank you again.

**Comment by bastilimbach** [comment]
No problem 😉 
You should take a look at [html-proofer](https://github.com/gjtorikian/html-proofer). Html proofer checks all your links and shows you if some links throw 404 errors. It's super simple to implement. If you're interested, I could create a PR for that.

**Pull request closed without merging**
